s=set()
n= input("Enter number:")
s.add(int(n))
s=set()
n= input("Enter number:")
s.add(int(n))
s=set()
n= input("Enter number:")
s.add(int(n))
s=set()
n= input("Enter number:")
s.add(int(n))
s=set()
n= input("Enter number:")
s.add(int(n))
s=set()
n= input("Enter number:")
s.add(int(n))
s=set()
n= input("Enter number:")
s.add(int(n))
s=set()
n= input("Enter number:")
s.add(int(n))

print(s)

